name: Actions Workflow

on: 
  repository_dispatch:
    types: [build]
  schedule:
    - cron: "0 20 * * 1"
  push:
    branches-ignore:
      - develop

    # branches: 
    #   - master
    #   - 'feature/*' #matches feature/featA, feature/featB
    #   - 'feature/**' #matches feature/featA/cat feature/featB/dogAndCat
    #   # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
  # pull_request:
  #   types: [ closed, assigned, opened]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
     steps:
      # - name: payload
      #   run: echo $${github.event.client_payload.env}}
      # - name: List files
      #   run:  |
      #     pwd
      #     ls
      #     echo $GITHUB_SHA
      #     echo $GITHUB_REPOSITORY
      #     echo $GITHUB_WORKSPACE
      #     echo ${{github.token}}
      #     # git clone git@github.com:$GITHUB_REPOSITORY
      #     # git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files after Checkout
        run:  |
          pwd
          ls
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Curry Blake
      - name: Log Greeting Time
        run: echo "${{steps.outputs.time}}"

