name: My first workflow
on: [ push]

jobs:
    print_hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello world"

            - name: Run multiple command
              run: |
                node -v
                npm -v

    parallel-jobs:
        runs-on: macos-latest
        steps:
            - name: sw version
              run: sw_vers
    

    dependent-jobs:
        runs-on: windows-latest
        needs: print_hello_world
        steps: 
            - name: run on powershell
              run: Write-output "Window Sttring"
