name: Shell commands

on: [push, pull_request]

jobs:
  check-env:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENV }}
    steps: 
      - name: echo env 
        run: echo "${{vars.ENV}}""
      
    
#       - name: python commands
#         run: |
#           import platform
#           print 
#           (platform.processor())
#         shell: python

#   run-windows-commands:
#     runs-on: windows-latest
#     needs: ['run-shell-commands']
#     steps:
#       - name: Directory Powershell
#         run: Get-Location
#       - name: Directory Bash
#         run: pwd
#         shell: bash


