name: Shell commands

on: [push, pull_request]

jobs:
  check-env-stage:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENV }}
    steps: 
      - name: echo env on stage
        run: |
          echo "${{vars.ENV}}"
          echo "${{vars.TWILIO_ID}}"
      
  check-env-preprod:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENV }}
    steps: 
      - name: echo env on preprod
        run: |
          echo "${{vars.ENV}}"
          echo "${{vars.TWILIO_ID}}"
#       - name: python commands
#         run: |
#           import platform
#           print 
#           (platform.processor())
#         shell: python

#   run-windows-commands:
#     runs-on: windows-latest
#     needs: ['run-shell-commands']
#     steps:
#       - name: Directory Powershell
#         run: Get-Location
#       - name: Directory Bash
#         run: pwd
#         shell: bash


