name: Workflow Commands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps: 
          - name: Setting an error message
            run: echo "::error::Missing semicolons"
        
          - name: Setting an error message with param
            run: echo "::error title=error title, file=app.js, line 2,endLine=3, col=5, endColumn=7::Missing semicolor"

          - name: Setting a debug message with param
            run: echo "::debug title=debug title, file=app.js, line 2,endLine=3, col=5, endColumn=7::Missing semicolor"

          - name: Group of logs
            run: |
                echo "::group::My group title"
                echo "Inside group"
                echo "::endgroup::"

          - name: Masking a value
            run: "::add-mask:: Secret String"
          
          - name: echo a secret
            run: echo "Secret String"


          - name: Send a message to Microsoft Teams
            uses: aliencube/microsoft-teams-actions@v0.8.0
            with:
              webhook_uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}
              title: API e2e test run on github actions
              summary: sh-usermanagement-serenityjs job integration test 
              text: "Test report for API automation Testing"
              theme_color: "003bd7"
              "sections": [{
                    "activityTitle": "Larry Bryant created a new task",
                    "activitySubtitle": "On Project Tango",
                    "activityImage": "https://adaptivecards.io/content/cats/3.png",
                    "facts": [{
                        "name": "Assigned to",
                        "value": "Unassigned"
                    }, {
                        "name": "Due date",
                        "value": "Mon May 01 2017 17:07:18 GMT-0700 (Pacific Daylight Time)"
                    }, {
                        "name": "Status",
                        "value": "Not started"
                    }],
                    "markdown": true
                }],
